{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2010-09-09T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-09-18T12:57:01",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289"
                },
                {
                    "name": "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200"
                },
                {
                    "name": "43068",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/43068"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://bugs.launchpad.net/zodb/+bug/135108"
                },
                {
                    "name": "ADV-2011-0212",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_VUPEN"
                    ],
                    "url": "http://www.vupen.com/english/advisories/2011/0212"
                },
                {
                    "name": "51040",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51040"
                },
                {
                    "name": "oval:org.mitre.oval:def:12210",
                    "tags": [
                        "vdb-entry",
                        "signature",
                        "x_refsource_OVAL"
                    ],
                    "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210"
                },
                {
                    "name": "50858",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/50858"
                },
                {
                    "name": "MDVSA-2010:216",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_MANDRIVA"
                    ],
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "http://bugs.python.org/issue9129"
                },
                {
                    "name": "44533",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/44533"
                },
                {
                    "name": "SUSE-SR:2011:002",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
                },
                {
                    "name": "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
                },
                {
                    "name": "USN-1596-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1596-1"
                },
                {
                    "name": "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://bugs.python.org/issue6706"
                },
                {
                    "name": "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
                },
                {
                    "name": "USN-1613-2",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1613-2"
                },
                {
                    "name": "SUSE-SR:2010:024",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "http://svn.python.org/view?view=rev&revision=84289"
                },
                {
                    "name": "51024",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51024"
                },
                {
                    "name": "USN-1613-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1613-1"
                },
                {
                    "name": "MDVSA-2010:215",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_MANDRIVA"
                    ],
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2010-3493",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289",
                            "refsource": "CONFIRM",
                            "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289"
                        },
                        {
                            "name": "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=632200",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200"
                        },
                        {
                            "name": "43068",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/43068"
                        },
                        {
                            "name": "https://bugs.launchpad.net/zodb/+bug/135108",
                            "refsource": "MISC",
                            "url": "https://bugs.launchpad.net/zodb/+bug/135108"
                        },
                        {
                            "name": "ADV-2011-0212",
                            "refsource": "VUPEN",
                            "url": "http://www.vupen.com/english/advisories/2011/0212"
                        },
                        {
                            "name": "51040",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/51040"
                        },
                        {
                            "name": "oval:org.mitre.oval:def:12210",
                            "refsource": "OVAL",
                            "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210"
                        },
                        {
                            "name": "50858",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/50858"
                        },
                        {
                            "name": "MDVSA-2010:216",
                            "refsource": "MANDRIVA",
                            "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216"
                        },
                        {
                            "name": "http://bugs.python.org/issue9129",
                            "refsource": "CONFIRM",
                            "url": "http://bugs.python.org/issue9129"
                        },
                        {
                            "name": "44533",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/44533"
                        },
                        {
                            "name": "SUSE-SR:2011:002",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
                        },
                        {
                            "name": "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
                        },
                        {
                            "name": "USN-1596-1",
                            "refsource": "UBUNTU",
                            "url": "http://www.ubuntu.com/usn/USN-1596-1"
                        },
                        {
                            "name": "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
                        },
                        {
                            "name": "http://bugs.python.org/issue6706",
                            "refsource": "MISC",
                            "url": "http://bugs.python.org/issue6706"
                        },
                        {
                            "name": "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
                        },
                        {
                            "name": "USN-1613-2",
                            "refsource": "UBUNTU",
                            "url": "http://www.ubuntu.com/usn/USN-1613-2"
                        },
                        {
                            "name": "SUSE-SR:2010:024",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html"
                        },
                        {
                            "name": "http://svn.python.org/view?view=rev&revision=84289",
                            "refsource": "CONFIRM",
                            "url": "http://svn.python.org/view?view=rev&revision=84289"
                        },
                        {
                            "name": "51024",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/51024"
                        },
                        {
                            "name": "USN-1613-1",
                            "refsource": "UBUNTU",
                            "url": "http://www.ubuntu.com/usn/USN-1613-1"
                        },
                        {
                            "name": "MDVSA-2010:215",
                            "refsource": "MANDRIVA",
                            "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-29T17:09:02.759Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200/DEMO_2024_06_19"
                    },
                    {
                        "name": "43068",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/43068/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugs.launchpad.net/zodb/+bug/135108/DEMO_2024_06_19"
                    },
                    {
                        "name": "ADV-2011-0212",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_VUPEN",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.vupen.com/english/advisories/2011/0212/DEMO_2024_06_19"
                    },
                    {
                        "name": "51040",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/51040/DEMO_2024_06_19"
                    },
                    {
                        "name": "oval:org.mitre.oval:def:12210",
                        "tags": [
                            "vdb-entry",
                            "signature",
                            "x_refsource_OVAL",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210/DEMO_2024_06_19"
                    },
                    {
                        "name": "50858",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/50858/DEMO_2024_06_19"
                    },
                    {
                        "name": "MDVSA-2010:216",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_MANDRIVA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://bugs.python.org/issue9129/DEMO_2024_06_19"
                    },
                    {
                        "name": "44533",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/44533/DEMO_2024_06_19"
                    },
                    {
                        "name": "SUSE-SR:2011:002",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3/DEMO_2024_06_19"
                    },
                    {
                        "name": "USN-1596-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1596-1/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://bugs.python.org/issue6706/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6/DEMO_2024_06_19"
                    },
                    {
                        "name": "USN-1613-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1613-2/DEMO_2024_06_19"
                    },
                    {
                        "name": "SUSE-SR:2010:024",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://svn.python.org/view?view=rev&revision=84289/DEMO_2024_06_19"
                    },
                    {
                        "name": "51024",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/51024/DEMO_2024_06_19"
                    },
                    {
                        "name": "USN-1613-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1613-1/DEMO_2024_06_19"
                    },
                    {
                        "name": "MDVSA-2010:215",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_MANDRIVA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200/adp-test-6-28"
                    },
                    {
                        "name": "43068",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/43068/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://bugs.launchpad.net/zodb/+bug/135108/adp-test-6-28"
                    },
                    {
                        "name": "ADV-2011-0212",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_VUPEN",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.vupen.com/english/advisories/2011/0212/adp-test-6-28"
                    },
                    {
                        "name": "51040",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/51040/adp-test-6-28"
                    },
                    {
                        "name": "oval:org.mitre.oval:def:12210",
                        "tags": [
                            "vdb-entry",
                            "signature",
                            "x_refsource_OVAL",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210/adp-test-6-28"
                    },
                    {
                        "name": "50858",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/50858/adp-test-6-28"
                    },
                    {
                        "name": "MDVSA-2010:216",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_MANDRIVA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://bugs.python.org/issue9129/adp-test-6-28"
                    },
                    {
                        "name": "44533",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.securityfocus.com/bid/44533/adp-test-6-28"
                    },
                    {
                        "name": "SUSE-SR:2011:002",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3/adp-test-6-28"
                    },
                    {
                        "name": "USN-1596-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1596-1/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://bugs.python.org/issue6706/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6/adp-test-6-28"
                    },
                    {
                        "name": "USN-1613-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1613-2/adp-test-6-28"
                    },
                    {
                        "name": "SUSE-SR:2010:024",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://svn.python.org/view?view=rev&revision=84289/adp-test-6-28"
                    },
                    {
                        "name": "51024",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/51024/adp-test-6-28"
                    },
                    {
                        "name": "USN-1613-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.ubuntu.com/usn/USN-1613-1/adp-test-6-28"
                    },
                    {
                        "name": "MDVSA-2010:215",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_MANDRIVA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2010-3493",
        "datePublished": "2010-10-19T19:00:00",
        "dateReserved": "2010-09-24T00:00:00",
        "dateUpdated": "2024-06-29T17:09:02.759Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}