{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2017-01-19T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2018-01-04T19:57:01",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/rohe/pysaml2/issues/366"
                },
                {
                    "name": "RHSA-2017:0936",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2017:0936"
                },
                {
                    "name": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5"
                },
                {
                    "name": "97692",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/97692"
                },
                {
                    "name": "DSA-3759",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "http://www.debian.org/security/2017/dsa-3759"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"
                },
                {
                    "name": "RHSA-2017:0938",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2017:0938"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/rohe/pysaml2/pull/379"
                },
                {
                    "name": "RHSA-2017:0937",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2017:0937"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2016-10149",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/rohe/pysaml2/issues/366",
                            "refsource": "MISC",
                            "url": "https://github.com/rohe/pysaml2/issues/366"
                        },
                        {
                            "name": "RHSA-2017:0936",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:0936"
                        },
                        {
                            "name": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5"
                        },
                        {
                            "name": "97692",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/97692"
                        },
                        {
                            "name": "DSA-3759",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2017/dsa-3759"
                        },
                        {
                            "name": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
                        },
                        {
                            "name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716",
                            "refsource": "CONFIRM",
                            "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"
                        },
                        {
                            "name": "RHSA-2017:0938",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:0938"
                        },
                        {
                            "name": "https://github.com/rohe/pysaml2/pull/379",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/rohe/pysaml2/pull/379"
                        },
                        {
                            "name": "RHSA-2017:0937",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:0937"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-30T18:29:11.442Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/rohe/pysaml2/issues/366/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2017:0936",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0936/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5/DEMO_2024_06_19"
                    },
                    {
                        "name": "97692",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/97692/DEMO_2024_06_19"
                    },
                    {
                        "name": "DSA-3759",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.debian.org/security/2017/dsa-3759/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2017:0938",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0938/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/rohe/pysaml2/pull/379/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2017:0937",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0937/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://github.com/rohe/pysaml2/issues/366/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2017:0936",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0936/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5/adp-test-6-28"
                    },
                    {
                        "name": "97692",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.securityfocus.com/bid/97692/adp-test-6-28"
                    },
                    {
                        "name": "DSA-3759",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.debian.org/security/2017/dsa-3759/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2017:0938",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0938/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://github.com/rohe/pysaml2/pull/379/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2017:0937",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2017:0937/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2016-10149",
        "datePublished": "2017-03-24T14:00:00",
        "dateReserved": "2017-01-19T00:00:00",
        "dateUpdated": "2024-06-30T18:29:11.442Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}