{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "ytnef",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "All versions"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "In ytnef 1.9.3, the TNEFSubjectHandler function in lib/ytnef.c allows remote attackers to cause a denial-of-service (and potentially code execution) due to a double free which can be triggered via a crafted file."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-416",
                            "description": "CWE-416",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-03-04T21:10:50",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1926967"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/Yeraze/ytnef/issues/85"
                }
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-07-03T21:17:02.626Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1926967/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/Yeraze/ytnef/issues/85/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1926967/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://github.com/Yeraze/ytnef/issues/85/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2021-3403",
        "datePublished": "2021-03-04T21:10:50",
        "dateReserved": "2021-02-09T00:00:00",
        "dateUpdated": "2024-07-03T21:17:02.626Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}