{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2014-01-24T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-08-25T17:57:02",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://pypi.python.org/pypi/kerberos"
                },
                {
                    "name": "74760",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/74760"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/apple/ccs-pykerberos/issues/31"
                }
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-30T15:46:37.825Z"
                },
                "references": [
                    {
                        "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://pypi.python.org/pypi/kerberos/DEMO_2024_06_19"
                    },
                    {
                        "name": "74760",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/74760/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/apple/ccs-pykerberos/issues/31/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://pypi.python.org/pypi/kerberos/adp-test-6-28"
                    },
                    {
                        "name": "74760",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.securityfocus.com/bid/74760/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://github.com/apple/ccs-pykerberos/issues/31/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2015-3206",
        "datePublished": "2017-08-25T18:00:00",
        "dateReserved": "2015-04-10T00:00:00",
        "dateUpdated": "2024-06-30T15:46:37.825Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}