{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2011-09-09T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2018-01-17T19:57:01",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "openSUSE-SU-2012:0653",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "https://hermes.opensuse.org/messages/14700881"
                },
                {
                    "name": "DSA-2332",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "http://www.debian.org/security/2011/dsa-2332"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366"
                },
                {
                    "name": "46614",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/46614"
                },
                {
                    "name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://openwall.com/lists/oss-security/2011/09/11/1"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.djangoproject.com/weblog/2011/sep/10/127/"
                },
                {
                    "name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://openwall.com/lists/oss-security/2011/09/13/2"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.djangoproject.com/weblog/2011/sep/09/"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2011-4138",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "openSUSE-SU-2012:0653",
                            "refsource": "SUSE",
                            "url": "https://hermes.opensuse.org/messages/14700881"
                        },
                        {
                            "name": "DSA-2332",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2011/dsa-2332"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=737366",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366"
                        },
                        {
                            "name": "46614",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/46614"
                        },
                        {
                            "name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                            "refsource": "MLIST",
                            "url": "http://openwall.com/lists/oss-security/2011/09/11/1"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2011/sep/10/127/",
                            "refsource": "CONFIRM",
                            "url": "https://www.djangoproject.com/weblog/2011/sep/10/127/"
                        },
                        {
                            "name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                            "refsource": "MLIST",
                            "url": "http://openwall.com/lists/oss-security/2011/09/13/2"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2011/sep/09/",
                            "refsource": "CONFIRM",
                            "url": "https://www.djangoproject.com/weblog/2011/sep/09/"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-29T20:13:54.987Z"
                },
                "references": [
                    {
                        "name": "openSUSE-SU-2012:0653",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://hermes.opensuse.org/messages/14700881/DEMO_2024_06_19"
                    },
                    {
                        "name": "DSA-2332",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.debian.org/security/2011/dsa-2332/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366/DEMO_2024_06_19"
                    },
                    {
                        "name": "46614",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/46614/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://openwall.com/lists/oss-security/2011/09/11/1/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2011/sep/10/127//DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://openwall.com/lists/oss-security/2011/09/13/2/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2011/sep/09//DEMO_2024_06_19"
                    },
                    {
                        "name": "openSUSE-SU-2012:0653",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://hermes.opensuse.org/messages/14700881/adp-test-6-28"
                    },
                    {
                        "name": "DSA-2332",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.debian.org/security/2011/dsa-2332/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366/adp-test-6-28"
                    },
                    {
                        "name": "46614",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/46614/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://openwall.com/lists/oss-security/2011/09/11/1/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2011/sep/10/127//adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://openwall.com/lists/oss-security/2011/09/13/2/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2011/sep/09//adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2011-4138",
        "datePublished": "2011-10-19T10:00:00",
        "dateReserved": "2011-10-19T00:00:00",
        "dateUpdated": "2024-06-29T20:13:54.987Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}